version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: docker
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: rest_with_asp_net
    ports:
      - 3308:3306
    networks:
      - erudio-network
      
  rest-with-asp-net:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: RESTWithASP-NET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:8081
      - 4430:8080
      
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge